name = input("enter you name:")
surname = input("enter you surname:")
age = input("enter you age:")
mom_name = input("enter mom name:")
dad_name = input("enter dad name:")
where_you_live = input("enter where live:")
what_you_hobby = input("enter you hobby:")

print(name)
print("you surname is " +surname )
print("you age is " + age)
print("you mom name is " + mom_name)
print("you dad name is " + dad_name)
print("you live is " + where_you_live)
print("you hobby is " + what_you_hobby)
